kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ${pgsql_instance_name}
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: ${VSPHERE_DATASTORE}
  diskformat: thin
  fstype: ext3
