kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory
  namespace: ${environment}
  annotations:
    volume.beta.kubernetes.io/storage-class: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${artifactory_pvc_size}