---
halyard:
  spinnakerVersion: ${spinnaker_app_version}
  image:
    repository: ${registry}/releng/halyard
    tag: ${halyard_image_version}

ingress:
  enabled: true
  host: ${spinnaker_external_host}

redis:
  external:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}

minio:
  enabled: false

s3:
  enabled: true
  endpoint: "http://${minio_host}:${minio_port}"
  accessKey: "${minio_access_key}"
  secretKey: "${minio_secret_key}"
  bucket: spinnaker
