kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: concourse-ci
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: ${VSPHERE_DATASTORE}
  diskformat: thin
  fstype: ext3
